### ISSUE TITLE
Changes in readme: The Plan

### ISSUE THREAD

**Issue by LordVicky** [skandtandon/Professional_Noob#1]
Once I reached the "The Plan" section, I thought I should follow it immediately, the next day when I scrolled down I knew the first section was just a plan of what I am going to do.

I would like to suggest a edit to define more of what The Plan really is:

```
## The Plan
This is what were going to do for the next couple of days/weeks, it is our summary of a gameplan.  
### Level 1: Intro (2 - 6 weeks)
First try programming to figure out if a programming career is right for you. 
* Step 1: Pick a first programming language (1 day)
* Step 2: Work through a short intro programming course (14 - 45 days)
* Step 3: Decide if you actually want to become a professional programmer (1 - 7 days)

```

Of course you could edit it with better words, but this is just what I thought would refine the guide even more.

**Comment by skandtandon** [comment]
Done
