### ISSUE TITLE
Changes to readme: Pick a first a pograming language

### ISSUE THREAD

**Issue by LordVicky** [skandtandon/Professional_Noob#2]
I would like to suggest a minor edit to this section, the text bellow could be moved to More Info section.

Before: 

**If you have hit the end of the day without choosing a language, I’m going to pick for you: Congratulations, you’re going to learn Python!**
## More Info
Context.

Now:

## More info:
Context
**If you have hit the end of the day without choosing a language, I’m going to pick for you: Congratulations, you’re going to learn Python!**

**Comment by skandtandon** [comment]
Okay that make sense
